### PR TITLE
Upgrade to USWDS v2

### PR DESCRIPTION
**Pull request by stvnrlly**
This pull request will takes the site from USWDS v1 to v2, with some tweaks and search powered by Search.gov.

A site preview is available at https://federalist-9dc074d2-9bb0-4720-8e37-036899ae1463.app.cloud.gov/preview/gsa-oes/office-of-evaluation-sciences/stvnrlly-upgrade-uswds/.

- [x] Update to last minor version of USWDS v1
- [x] Update to USWDS v2
- [x] Add search function via search.gov
- [ ] Create new page(s) for Evidence Act work
- [x] Change sort function on team page to highlight current team
- [x] Sort projects by year
- [ ] Make wider use of Jekyll collections
- [x] Use Lato font throughout the site

Remaining issues from #275 merge:

- [x] Re-add the toolkit page's custom styling && CSS class migration
- [x] Fix the columns on the contact page
- [ ] Check colors and typography, which changed with v2 defaults
- [x] Switch from base layout to USWDS default layout

### CODE REVIEW

**Comment by amirbey** [comment]
@stvnrlly - do you have a special ruby version requirement? fyi, the site builds will be much faster if you do not specify the .ruby-version which will build using the default ruby version supported by Federalist (currently 2.6.x)

**Comment by stvnrlly** [comment]
No special version requirement, just a general preference for pinning versions for other developers. Happy to switch that here for faster builds and just put it in the documentation.

If I remember correctly, Bundler is the opposite, and pinning the Bundler version to something specific will help take advantage of caching. Is that right?

**Comment by amirbey** [comment]
pinning bundler may still be necessary ... especially if developers are not using the Federalist default version locally.  luckily, bundler installation takes no where as long to install as ruby installation

**Comment by stvnrlly** [comment]
Okay, this is free of conflicts and should be mergeable.

The colors and styling is not quite the same as the current site, with small differences due to new USWDS defaults. This can probably be cleaned up without too much issue, but I'm not sure how important continuity is. Since there are lots of code changes, other work on the site in the meantime has a decent chance of creating new conflicts, so if continuity is desired it'll be a good idea to all get together and get the styling worked out quickly.

There's also more updates to make according to the update plan, but similarly, it's worthwhile to get this merged down to prevent future conflicts.

**Pull request closed without merging**
